Refs #2 DEV: Allow User to comment to Micropost
EricNguyen123/app_test pull request #6
Opened 2024-01-04 02:29 UTC by EricNguyen123

###### Resolved (Brief Summary of PR)
- [x] Design the ERD necessary for this task
- [x] Add function to allow user to comment
- [x] Write Test
###### Solution (How PR fix or DRY code)

https://github.com/EricNguyen123/app_test/assets/101819723/835e42c2-447e-4d1d-b7ba-63a5f066fb5b

https://github.com/EricNguyen123/app_test/assets/101819723/c4f99c46-9e5b-4a14-8660-9dae5c1e25d0

2024-01-04 02:34 UTC, NishaLab commented on app/controllers/microposts_controller.rb
> +    delete_cmt(@micropost.id)
Use `dependent` in model relation to handle delete child

2024-01-04 02:34 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +        post :create, params: { micropost: { micropost_id: micropost.id, user_id: user.id } }
This test checks for micropost but does not check if a comment is created.

2024-01-04 02:34 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +        post :create, params: { micropost: { micropost_id: micropost.id, image: } }
this case does not pass image to image parameter ?

2024-01-04 02:34 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +        post :create, params: { micropost: { content: nil } }
Check the DB for change in model count to make sure no micropost is created

2024-01-04 02:34 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +        post :create, params: { micropost: { content: micropost.content, user_id: micropost.user_id } }
add check the DB if there is a post created

2024-01-04 02:34 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +
Miss case when delete micropost with comment or comment with comment?

2024-01-04 02:34 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +        delete :destroy, params: { id: micropost.id }
Check the DB if the post is actually deleted

2024-01-04 04:49 UTC, Bunbu-NamT commented on app/assets/stylesheets/custom.scss
> +    background-color: #f9f9f9;
Please define color name.

2024-01-04 04:49 UTC, Bunbu-NamT commented on app/assets/stylesheets/custom.scss
> +                color: #4376a6;
same

2024-01-04 04:49 UTC, Bunbu-NamT commented on app/assets/stylesheets/custom.scss
> +        border-left: solid 1px #bbb;
same

2024-01-04 04:49 UTC, Bunbu-NamT commented on app/models/micropost.rb
> +  has_many :microposts
`has_many :microposts, dependent: :destroy`

2024-01-04 06:30 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +        expect(assigns(:micropost)).to be_a_new(Micropost)
be_a_new only checks if a model is initialized not saved
https://rubydoc.info/gems/rspec-rails/RSpec%2FRails%2FMatchers:be_a_new

2024-01-05 14:45 UTC, EricNguyen123 commented
https://github.com/EricNguyen123/app_test/assets/101819723/1b4143b6-2faa-4651-a160-1b6a2afe93ba

2024-01-08 01:58 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +      @feed_items = current_user.feed.where(micropost_id: nil).paginate(page: params[:page])
use scope for `where(micropost_id: nil)`

2024-01-08 01:58 UTC, Bunbu-NamT commented on app/models/micropost.rb
> +  validates :micropost_id, presence: false
We don't need to use `validate` if `presence: false`

2024-01-08 02:03 UTC, Bunbu-NamT commented on app/views/shared/_edit_form.html.erb
> +<script type="text/javascript">
Don't use any javascript or css code in html file.

2024-01-08 02:03 UTC, Bunbu-NamT commented on app/views/shared/_reply.html.erb
> +        <script type="text/javascript">
Don't use any javascript or css code in html file.

2024-01-08 02:03 UTC, Bunbu-NamT commented on app/views/shared/_reply_form.html.erb
> +<script type="text/javascript">
Don't use any javascript or css code in html file.

2024-01-08 04:37 UTC, NishaLab commented on spec/controllers/micropost_controller_spec.rb
> +
Move this to spec/models/micropost_spec.rb for that is a model test

2024-01-09 06:38 UTC, Bunbu-NamT commented on app/javascript/edit_form_reply.js
> +    var formEditId = $(this).attr('id');
Please check when to use let, var, const. Basically, only let and const should be used.

2024-01-09 06:38 UTC, Bunbu-NamT commented on spec/models/micropost_spec.rb
> +    micropost.user_id = nil
Please use gem https://github.com/thoughtbot/shoulda-matchers

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +    if params[:micropost][:micropost_id]
I think just `@micropost = current_user.microposts.build(micropost_params)` is ok

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +    @micropost.destroy!
When does an error occur when destroying?
Also, I haven't seen you handle any errors.

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +    micropost = Micropost.find_by(id: params[:micropost][:id])
You can use before action correct_user instead of like this.

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +    @micropost.image.attach(params[:micropost][:image]) if params[:micropost][:image]
Why you need attach image here?

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +    render json: { success: true, micropost:, html_content: }
I think this causes the error.

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/microposts_controller.rb
> +    render json: { success: true, micropost:, html_content: }
same

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/controllers/static_pages_controller.rb
> +    @feed_items = current_user.feed.without_micropost_id.paginate(page: params[:page], per_page: 6)
why you use per_page = 6 ?

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/views/shared/_reply_form.html.erb
> +<%= javascript_include_tag "form_post_reply", "data-track-turbo": "true", defer: true %>
This script is rendered every time there is a new comment. This makes the DOM very heavy.
There is a rule to remember, never write scripts or embed scripts in the DOM.

2024-01-10 02:36 UTC, Bunbu-NamT commented on app/views/shared/_user_info.html.erb
> +<span><%= pluralize(current_user.microposts.where(micropost_id: nil).count, "micropost") %></span>
you can use scope without_micropost_id

2024-01-10 02:37 UTC, Bunbu-NamT requested changes
Please use simplecov to check if rspec has 100% coverage of the controller code. I don't think it gets enough coverage.

2024-01-10 03:41 UTC, EricNguyen123 commented
I used Simplecov for the controller code and the coverage is 100%

2024-01-11 06:18 UTC, Bunbu-NamT approved these changes

2024-01-11 06:26 UTC, merged